baseURL = ""
relativeURLs = true

languageCode = "de-de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
[languages]
  [languages.de]
    weight = 1
    languageName = "DE"
    title = "evcc - Smart laden ☀️🚘 - Intelligentes Energiemanagement für Zuhause"
    [languages.de.params]
      docsUrl = "https://docs.evcc.io/docs/Home"
      blogUrl = "https://docs.evcc.io/blog"
  [languages.en]
    weight = 2
    languageName = "EN"
    title = "evcc - Smart Charging ☀️🚘 - Intelligent Energy Management for Your Home"
    [languages.en.params]
      docsUrl = "https://docs.evcc.io/en/docs/Home"
      blogUrl = "https://docs.evcc.io/en/blog"
[site]
  [params]
  description = "evcc ermöglicht es, Elektrofahrzeuge mit möglichst viel selbsterzeugtem Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true

[security]
  [security.funcs]
    getenv = ["SLACK_INVITE_URL"]
